# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(520, 484)
        Form.setStyleSheet("background-color: rgb(255, 244, 248);")
        self.countPassengers = QtWidgets.QPushButton(parent=Form)
        self.countPassengers.setGeometry(QtCore.QRect(150, 310, 211, 61))
        self.countPassengers.setStyleSheet("background-color: rgb(255, 225, 240);")
        self.countPassengers.setObjectName("countPassengers")
        self.countRoetes = QtWidgets.QPushButton(parent=Form)
        self.countRoetes.setGeometry(QtCore.QRect(150, 390, 211, 61))
        self.countRoetes.setStyleSheet("background-color: rgb(255, 225, 240);")
        self.countRoetes.setObjectName("countRoetes")
        self.saveExel = QtWidgets.QPushButton(parent=Form)
        self.saveExel.setGeometry(QtCore.QRect(400, 430, 111, 41))
        self.saveExel.setStyleSheet("background-color: rgb(255, 225, 240);")
        self.saveExel.setObjectName("saveExel")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 471, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "examProgramm"))
        self.countPassengers.setText(_translate("Form", "Посчитать количество пассажиров"))
        self.countRoetes.setText(_translate("Form", "Посчитать количество рейсов"))
        self.saveExel.setText(_translate("Form", "Сохранить в Excel"))
